name: Fast Video Loop

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render Fast
        run: |
          # Preset ultrafast se 22 min ki video minutes mein banegi
          # -shortest se audio khatam hote hi process stop ho jayega
          ffmpeg -re -stream_loop -1 -i video.mp4 -i audio.mp3 -map 0:v:0 -map 1:a:0 -c:v libx264 -preset ultrafast -crf 28 -c:a copy -shortest final_output.mp4

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: My-Video
          path: final_output.mp4
          retention-days: 1
          
